import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./_components/Navbar";
import Footer from "./_components/Footer";

export const metadata: Metadata = {
  title: "Healthcare Group",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` antialiased text-balance bg-lightBg`}>
        <div>
          <Navbar />
          <main className="overflow-hidden">{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
